import 'package:path/path.dart' as p;

import 'models.dart';

/// Renders GitHub Flavored Markdown report.
String renderMarkdownReport(List<GhPr> prs, {DateTime? currentTime}) {
  final now = currentTime ?? DateTime.now();
  final categorized = categorizePullRequests(prs);

  const link =
      'file:///usr/local/google/home/kevmoo/github/kevmoo/scripts.dart/bin/gh_view.dart';
  final buffer = StringBuffer()
    ..writeln('# 🐙 GitHub Pull Request Overview Dashboard')
    ..writeln()
    ..writeln(
      'Generated by [`gh-view`]($link) | Scope: `@me` (All GitHub Orgs)',
    )
    ..writeln()
    ..writeln('---')
    ..writeln()
    ..writeln('## 📊 High-Level Summary')
    ..writeln()
    ..writeln('<!-- mdformat off(prevent table wrapping) -->')
    ..writeln('| Metric | Count | Status Description |')
    ..writeln('| :--- | :---: | :--- |')
    ..writeln(
      '| **Total Open PRs** | **${prs.length}** | '
      'Active pull requests across all GitHub organizations |',
    )
    ..writeln(
      '| 🚀 **Ready to Merge** | **${categorized.readyToMerge.length}** | '
      'Approved by reviewers, passing all CI checks, and mergeable |',
    )
    ..writeln(
      '| ⚠️ **Action Needed** | **${categorized.actionNeeded.length}** | '
      'Blocked by failing CI, changes requested, or merge conflicts |',
    )
    ..writeln(
      '| 🟡 **In Review Queue** | **${categorized.inReview.length}** | '
      'Active non-draft PRs with green/pending CI awaiting review |',
    )
    ..writeln(
      '| ⚪ **Drafts & WIP** | **${categorized.drafts.length}** | '
      'Work-in-progress draft pull requests |',
    )
    ..writeln(
      '| 📦 **Archived Repositories** | **${categorized.archived.length}** | '
      'Pull requests in archived/read-only repositories |',
    )
    ..writeln('<!-- mdformat on -->')
    ..writeln();

  if (prs.isEmpty) {
    buffer.writeln('No open pull requests found. 🎉\n');
    return buffer.toString();
  }

  _writeMarkdownSection(
    buffer,
    title: '## 🚀 1. Ready to Merge (Approved + Green CI + Mergeable)',
    prs: categorized.readyToMerge,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title:
        '## ⚠️ 2. Action Needed '
        '(Blocked / Failing CI / Conflicts / Changes Requested)',
    prs: categorized.actionNeeded,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title: '## 🟡 3. In Review Queue (Green CI + Active Review)',
    prs: categorized.inReview,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title:
        '## ⚪ 4. Drafts & Work In Progress (${categorized.drafts.length} PRs)',
    prs: categorized.drafts,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title:
        '## 📦 5. Archived Repositories (Read-Only) '
        '(${categorized.archived.length} PRs)',
    prs: categorized.archived,
    now: now,
  );

  return buffer.toString();
}

void _writeMarkdownSection(
  StringBuffer buffer, {
  required String title,
  required List<GhPr> prs,
  required DateTime now,
}) {
  if (prs.isEmpty) return;
  const tableHeader = '''
<!-- mdformat off(prevent table wrapping) -->
| PR & Repository | Branch & Local Mapping | Review & CI Status | Last Touched | Action / Ping Status |
| :--- | :--- | :--- | :--- | :--- |''';

  buffer
    ..writeln(title)
    ..writeln()
    ..writeln(tableHeader);
  for (final pr in prs) {
    _writeMarkdownPrRow(buffer, pr, now);
  }
  buffer
    ..writeln('<!-- mdformat on -->')
    ..writeln();
}

void _writeMarkdownPrRow(StringBuffer buffer, GhPr pr, DateTime now) {
  final repoUrl = pr.repoUrl.isNotEmpty
      ? pr.repoUrl
      : 'https://github.com/${pr.repository}';
  final queuePrefix = pr.isInMergeQueue ? '`[🔀 Merge Queue]` ' : '';
  final sanitizedTitle = pr.title
      .replaceAll('|', '/')
      .replaceAll('\n', ' ')
      .trim();

  final prLines = <String>[
    if (pr.context != null && pr.context!.trim().isNotEmpty) ...[
      pr.context!
          .trim()
          .replaceAll('|', '/')
          .replaceAll('\r\n', '\n')
          .replaceAll('\n', '<br>'),
      '',
    ],
    '[#${pr.number}](${pr.url}) $queuePrefix$sanitizedTitle',
    '[${pr.repository}]($repoUrl)',
  ];

  final branchLines = <String>[
    '`${pr.headRefName}`',
    _formatLocalMappingMarkdown(pr.localStatus),
  ];

  final areThreadsResolved =
      pr.totalReviewThreads > 0 && pr.unresolvedReviewThreads == 0;
  final isReady = isReadyToMerge(pr);

  final statusLines = <String>[
    'Review: ${_formatReviewBadgeMarkdown(pr, areThreadsResolved)}',
    'CI: ${_formatCiBadgeMarkdown(pr.ciStatus)}',
    'Merge: ${_formatMergeableBadgeMarkdown(pr)}',
  ];

  final touched = formatTouchedMarkdown(pr.updatedAt, currentTime: now);
  final actionItem = _resolveActionItemMarkdown(
    pr,
    areThreadsResolved: areThreadsResolved,
    isReadyToMerge: isReady,
    now: now,
  );

  final prCell = prLines.join('<br>');
  final branchCell = branchLines.join('<br>');
  final statusCell = statusLines
      .map((line) => line.replaceAll(' ', '&nbsp;'))
      .join('<br>');

  buffer.writeln(
    '| $prCell | $branchCell | $statusCell | $touched | $actionItem |',
  );
}

String _resolveActionItemMarkdown(
  GhPr pr, {
  required bool areThreadsResolved,
  required bool isReadyToMerge,
  required DateTime now,
}) {
  if (pr.isRepoArchived) return '📦 Archived repo (read-only)';
  if (isReadyToMerge) return '🚀 **Ready to merge**';
  if (pr.isBlockedByProtection) {
    return '🧱 **Blocked by ruleset/branch protection**';
  }

  final reviewers = pr.targetReviewers;
  final hasReviewers = reviewers.isNotEmpty;
  final reviewersText = hasReviewers ? '@${reviewers.join(', @')}' : '';

  return switch ((
    pr.mergeable == MergeableState.conflicting,
    pr.ciStatus == CiStatus.failure,
    pr.reviewDecision,
    hasReviewers,
    areThreadsResolved,
    pr.unresolvedReviewThreads,
    pr.isDraft,
  )) {
    (true, _, _, _, _, _, true) => '⚠️ **Conflicting** (draft)',
    (true, _, _, _, _, _, false) => '⚠️ **Conflicting** (needs rebase)',
    (_, true, _, _, _, _, true) => '🔴 **CI Failing** (draft)',
    (_, true, _, _, _, _, false) => '🔴 **CI Failing** (needs fix)',
    (_, _, ReviewDecision.changesRequested, true, _, _, _) =>
      '🟡 **Re-review Requested** ($reviewersText)',
    (_, _, ReviewDecision.changesRequested, false, true, _, _) =>
      '🔄 **Re-review Needed** (threads resolved)',
    (_, _, ReviewDecision.changesRequested, false, false, > 0, _) =>
      '🔴 **Changes Requested** (${pr.unresolvedReviewThreads} open '
          'thread${pr.unresolvedReviewThreads > 1 ? 's' : ''})',
    (_, _, ReviewDecision.changesRequested, false, false, _, _) =>
      '🔴 **Changes Requested**',
    (_, _, ReviewDecision.reviewRequired || ReviewDecision.none, _, _, _, _) =>
      _resolveReviewRequiredActionMarkdown(
        pr,
        reviewersText: reviewersText,
        areThreadsResolved: areThreadsResolved,
        now: now,
      ),
    (_, _, _, _, _, _, true) => '⚪ **Work in progress**',
    _ => '⚪ **Active**',
  };
}

bool _isRecentPing(GhPr pr, DateTime now) {
  if (!pr.isAlreadyPinged) return false;
  final authorComment = pr.lastAuthorCommentAt;
  if (authorComment == null) return false;
  return now.difference(authorComment).inDays < 7;
}

String _resolveReviewRequiredActionMarkdown(
  GhPr pr, {
  required String reviewersText,
  required bool areThreadsResolved,
  required DateTime now,
}) {
  if (_isRecentPing(pr, now)) {
    final pingAge = formatTimeAgo(pr.lastAuthorCommentAt!, currentTime: now);
    if (reviewersText.isNotEmpty) {
      return '⏳ **Awaiting $reviewersText** (pinged $pingAge)';
    }
    return '⏳ **Awaiting Review** (pinged $pingAge)';
  }
  if (areThreadsResolved) {
    if (reviewersText.isNotEmpty) {
      return '🔔 **Ping Reviewer** ($reviewersText)';
    }
    return '🔔 **Ping Reviewer** (threads resolved)';
  }
  if (reviewersText.isNotEmpty) {
    return '⏳ **Awaiting $reviewersText**';
  }
  if (pr.isDraft) {
    return '⚪ **Work in progress**';
  }
  return '⏳ **Awaiting review**';
}

String _formatReviewBadgeMarkdown(GhPr pr, bool areThreadsResolved) {
  if (pr.reviewDecision == ReviewDecision.approved) return '🟢 Approved';
  if (pr.reviewDecision == ReviewDecision.changesRequested) {
    if (pr.targetReviewers.isNotEmpty) {
      return '🟡 Re-review Requested (@${pr.targetReviewers.join(', @')})';
    }
    if (areThreadsResolved) return '🔴 Changes Requested (Resolved)';
    if (pr.unresolvedReviewThreads > 0) {
      return '🔴 Changes Requested (${pr.unresolvedReviewThreads} open)';
    }
    return '🔴 Changes Requested';
  }
  if (pr.reviewDecision == ReviewDecision.reviewRequired) {
    if (pr.targetReviewers.isNotEmpty) {
      return '🟡 Review Required (@${pr.targetReviewers.join(', @')})';
    }
    return '🟡 Review Required';
  }
  return '⚪ None';
}

String _formatCiBadgeMarkdown(CiStatus ciStatus) => switch (ciStatus) {
  CiStatus.success => '🟢 Passing',
  CiStatus.treeBroken => '🟠 Tree Broken (PR Clean)',
  CiStatus.failure => '🔴 Failing',
  CiStatus.pending => '⏳ Pending',
  _ => '⚪ None',
};

String _formatMergeableBadgeMarkdown(GhPr pr) {
  if (pr.isBlockedMergeState) {
    return '🧱 Blocked';
  }

  final label = switch (pr.mergeable) {
    MergeableState.mergeable => '✅ Yes',
    MergeableState.conflicting => '⚠️ Conflicting',
    _ => pr.isInMergeQueue ? '✅ Yes' : '⚪ Unknown',
  };
  return pr.isInMergeQueue ? '$label (🔀 Queue)' : label;
}

String _formatLocalMappingMarkdown(LocalBranchStatus? loc) {
  if (loc == null) return 'Local: ⚪ Not checked out';
  final dirName = p.basename(loc.repoPath);
  return 'Local: ${loc.displayStatus} ([$dirName](file://${loc.repoPath}))';
}
