import 'dart:convert';

import 'package:io/ansi.dart';
import 'package:path/path.dart' as p;

import '../gh_view.dart';
import '../shared/markdown_table.dart';

/// Renders GitHub Flavored Markdown report.
String renderMarkdownReport(List<GhPr> prs, {DateTime? currentTime}) {
  final now = currentTime ?? DateTime.now();
  final categorized = categorizePullRequests(prs);

  const link =
      'file:///usr/local/google/home/kevmoo/github/kevmoo/scripts.dart/bin/gh_view.dart';
  final buffer = StringBuffer()
    ..writeln('# 🐙 GitHub Pull Request Overview Dashboard')
    ..writeln()
    ..writeln(
      'Generated by [`gh-view`]($link) | Scope: `@me` (All GitHub Orgs)',
    )
    ..writeln()
    ..writeln('---')
    ..writeln()
    ..writeln('## 📊 High-Level Summary')
    ..writeln()
    ..writeln('<!-- mdformat off(prevent table wrapping) -->')
    ..writeln('| Metric | Count | Status Description |')
    ..writeln('| :--- | :---: | :--- |')
    ..writeln(
      '| **Total Open PRs** | **${prs.length}** | '
      'Active pull requests across all GitHub organizations |',
    )
    ..writeln(
      '| 🚀 **Ready to Merge** | **${categorized.readyToMerge.length}** | '
      'Approved by reviewers, passing all CI checks, and mergeable |',
    )
    ..writeln(
      '| ⚠️ **Action Needed** | **${categorized.actionNeeded.length}** | '
      'Blocked by failing CI, changes requested, or merge conflicts |',
    )
    ..writeln(
      '| 🟡 **In Review Queue** | **${categorized.inReview.length}** | '
      'Active non-draft PRs with green/pending CI awaiting review |',
    )
    ..writeln(
      '| ⚪ **Drafts & WIP** | **${categorized.drafts.length}** | '
      'Work-in-progress draft pull requests |',
    )
    ..writeln(
      '| 📦 **Archived Repositories** | **${categorized.archived.length}** | '
      'Pull requests in archived/read-only repositories |',
    )
    ..writeln('<!-- mdformat on -->')
    ..writeln();

  if (prs.isEmpty) {
    buffer.writeln('No open pull requests found. 🎉\n');
    return buffer.toString();
  }

  _writeMarkdownSection(
    buffer,
    title: '## 🚀 1. Ready to Merge (Approved + Green CI + Mergeable)',
    prs: categorized.readyToMerge,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title:
        '## ⚠️ 2. Action Needed '
        '(Blocked / Failing CI / Conflicts / Changes Requested)',
    prs: categorized.actionNeeded,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title: '## 🟡 3. In Review Queue (Green CI + Active Review)',
    prs: categorized.inReview,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title:
        '## ⚪ 4. Drafts & Work In Progress (${categorized.drafts.length} PRs)',
    prs: categorized.drafts,
    now: now,
  );

  _writeMarkdownSection(
    buffer,
    title:
        '## 📦 5. Archived Repositories (Read-Only) '
        '(${categorized.archived.length} PRs)',
    prs: categorized.archived,
    now: now,
  );

  return buffer.toString();
}

void _writeMarkdownSection(
  StringBuffer buffer, {
  required String title,
  required List<GhPr> prs,
  required DateTime now,
}) {
  if (prs.isEmpty) return;
  const tableHeader = '''
<!-- mdformat off(prevent table wrapping) -->
| PR & Repository | Branch & Local Mapping | Review & CI Status | Last Touched | Action / Ping Status |
| :--- | :--- | :--- | :--- | :--- |''';

  buffer
    ..writeln(title)
    ..writeln()
    ..writeln(tableHeader);
  for (final pr in prs) {
    _writeMarkdownPrRow(buffer, pr, now);
  }
  buffer
    ..writeln('<!-- mdformat on -->')
    ..writeln();
}

void _writeMarkdownPrRow(StringBuffer buffer, GhPr pr, DateTime now) {
  final repoUrl = pr.repoUrl.isNotEmpty
      ? pr.repoUrl
      : 'https://github.com/${pr.repository}';
  final queuePrefix = pr.isInMergeQueue ? '`[🔀 Merge Queue]` ' : '';
  final sanitizedTitle = sanitizeMarkdownCell(pr.title);

  final prLines = <String>[
    if (pr.context != null && pr.context!.trim().isNotEmpty) ...[
      sanitizeMarkdownCell(pr.context!, newlinesToBr: true),
      '',
    ],
    '[#${pr.number}](${pr.url}) $queuePrefix$sanitizedTitle',
    '[${pr.repository}]($repoUrl)',
  ];

  final branchLines = <String>[
    '`${pr.headRefName}`',
    _formatLocalMappingMarkdown(pr.localStatus),
  ];

  final areThreadsResolved =
      pr.totalReviewThreads > 0 && pr.unresolvedReviewThreads == 0;
  final isReady = isReadyToMerge(pr);

  final statusLines = <String>[
    'Review: ${_formatReviewBadgeMarkdown(pr, areThreadsResolved)}',
    'CI: ${_formatCiBadgeMarkdown(pr.ciStatus)}',
    'Merge: ${_formatMergeableBadgeMarkdown(pr)}',
  ];

  final touched = formatTouchedMarkdown(pr.updatedAt, currentTime: now);
  final actionItem = _resolveActionItemMarkdown(
    pr,
    areThreadsResolved: areThreadsResolved,
    isReadyToMerge: isReady,
    now: now,
  );

  final prCell = prLines.join('<br>');
  final branchCell = branchLines.join('<br>');
  final statusCell = statusLines
      .map((line) => line.replaceAll(' ', '&nbsp;'))
      .join('<br>');

  buffer.writeln(
    '| $prCell | $branchCell | $statusCell | $touched | $actionItem |',
  );
}

String _resolveActionItemMarkdown(
  GhPr pr, {
  required bool areThreadsResolved,
  required bool isReadyToMerge,
  required DateTime now,
}) {
  if (pr.isRepoArchived) return '📦 Archived repo (read-only)';
  if (isReadyToMerge) return '🚀 **Ready to merge**';
  if (pr.isBlockedByProtection) {
    return '🧱 **Blocked by ruleset/branch protection**';
  }

  final reviewers = pr.targetReviewers;
  final hasReviewers = reviewers.isNotEmpty;
  final reviewersText = hasReviewers ? '@${reviewers.join(', @')}' : '';
  final hasRequestedReviewers =
      pr.requestedReviewers.isNotEmpty && pr.unrequestedActiveReviewers.isEmpty;

  if (pr.mergeable != MergeableState.conflicting &&
      pr.ciStatus == CiStatus.actionRequired) {
    return _formatCiActionMarkdown(pr);
  }

  return switch ((
    pr.mergeable == MergeableState.conflicting,
    pr.ciStatus == CiStatus.failure,
    pr.reviewDecision,
    pr.isDraft,
  )) {
    (true, _, _, true) => '⚠️ **Conflicting** (draft)',
    (true, _, _, false) => '⚠️ **Conflicting** (needs rebase)',
    (_, true, _, _) => _formatCiFailingMarkdown(pr),
    (_, _, ReviewDecision.changesRequested, _) =>
      _formatChangesRequestedActionMarkdown(
        pr,
        reviewersText: reviewersText,
        hasRequestedReviewers: hasRequestedReviewers,
        areThreadsResolved: areThreadsResolved,
      ),
    (_, _, ReviewDecision.reviewRequired || ReviewDecision.none, _) =>
      _resolveReviewRequiredActionMarkdown(
        pr,
        reviewersText: reviewersText,
        areThreadsResolved: areThreadsResolved,
        now: now,
      ),
    (_, _, _, true) => '⚪ **Work in progress**',
    _ => '⚪ **Active**',
  };
}

String _formatCiActionMarkdown(GhPr pr) {
  final detail = _sanitizeMarkdownCellDetail(pr.ciDetail);
  if (detail != null) {
    final prefix = pr.isDraft ? 'draft · ' : '';
    return '🟠 **CI Action Required** ($prefix$detail)';
  }
  return pr.isDraft
      ? '🟠 **CI Action Required** (draft)'
      : '🟠 **CI Action Required** (needs manual trigger/approval)';
}

String _formatCiFailingMarkdown(GhPr pr) {
  final detail = _sanitizeMarkdownCellDetail(pr.ciDetail);
  if (detail != null) {
    final prefix = pr.isDraft ? 'draft · ' : '';
    return '🔴 **CI Failing** ($prefix$detail)';
  }
  return pr.isDraft
      ? '🔴 **CI Failing** (draft)'
      : '🔴 **CI Failing** (needs fix)';
}

String? _sanitizeMarkdownCellDetail(String? detail) {
  if (detail == null) return null;
  final cleaned = sanitizeMarkdownCell(detail);
  return cleaned.isEmpty ? null : cleaned;
}

String _formatChangesRequestedActionMarkdown(
  GhPr pr, {
  required String reviewersText,
  required bool hasRequestedReviewers,
  required bool areThreadsResolved,
}) {
  if (pr.needsReviewReRequest) {
    return '🔄 **Re-request Review** '
        '(@${pr.unrequestedActiveReviewers.join(', @')})';
  }
  if (hasRequestedReviewers) {
    return '🟡 **Re-review Requested** ($reviewersText)';
  }
  if (areThreadsResolved && pr.hasAuthorRespondedSinceLastReview) {
    return '🔄 **Re-review Needed** (threads resolved)';
  }
  final crReviewers = pr.changesRequestedReviewers;
  final crReviewersText = crReviewers.isNotEmpty
      ? '@${crReviewers.join(', @')}'
      : '';
  if (pr.unresolvedReviewThreads > 0) {
    final suffix = crReviewersText.isNotEmpty ? ' · $crReviewersText' : '';
    final plural = pr.unresolvedReviewThreads > 1 ? 's' : '';
    return '🔴 **Changes Requested** '
        '(${pr.unresolvedReviewThreads} open thread$plural$suffix)';
  }
  return crReviewersText.isNotEmpty
      ? '🔴 **Changes Requested** ($crReviewersText)'
      : '🔴 **Changes Requested**';
}

bool _isRecentPing(GhPr pr, DateTime now) {
  if (!pr.isAlreadyPinged) return false;
  final authorComment = pr.lastAuthorCommentAt;
  if (authorComment == null) return false;
  return now.difference(authorComment).inDays < 7;
}

String _resolveReviewRequiredActionMarkdown(
  GhPr pr, {
  required String reviewersText,
  required bool areThreadsResolved,
  required DateTime now,
}) {
  if (pr.needsReviewReRequest) {
    final unrequestedText = '@${pr.unrequestedActiveReviewers.join(', @')}';
    return '🔄 **Re-request Review** ($unrequestedText)';
  }
  if (_isRecentPing(pr, now)) {
    final pingAge = formatTimeAgo(pr.lastAuthorCommentAt!, currentTime: now);
    if (reviewersText.isNotEmpty) {
      return '⏳ **Awaiting $reviewersText** (pinged $pingAge)';
    }
    return '⏳ **Awaiting Review** (pinged $pingAge)';
  }
  if (areThreadsResolved) {
    if (reviewersText.isNotEmpty) {
      return '🔔 **Ping Reviewer** ($reviewersText)';
    }
    return '👤 **Request Reviewer** (threads resolved, none in queue)';
  }
  if (reviewersText.isNotEmpty) {
    return '⏳ **Awaiting $reviewersText**';
  }
  if (pr.isDraft) {
    return '⚪ **Work in progress**';
  }
  return '👤 **Request Reviewer** (none in queue)';
}

String _formatReviewBadgeMarkdown(GhPr pr, bool areThreadsResolved) =>
    switch (pr.reviewDecision) {
      ReviewDecision.approved => '🟢 Approved',
      ReviewDecision.changesRequested when pr.needsReviewReRequest =>
        '🔴 Changes Requested · Re-request '
            '(@${pr.unrequestedActiveReviewers.join(', @')})',
      ReviewDecision.changesRequested
          when pr.requestedReviewers.isNotEmpty &&
              pr.unrequestedActiveReviewers.isEmpty =>
        '🟡 Re-review Requested (@${pr.targetReviewers.join(', @')})',
      ReviewDecision.changesRequested
          when areThreadsResolved && pr.hasAuthorRespondedSinceLastReview =>
        '🔴 Changes Requested (Resolved)',
      ReviewDecision.changesRequested when pr.unresolvedReviewThreads > 0 =>
        '🔴 Changes Requested (${pr.unresolvedReviewThreads} open)',
      ReviewDecision.changesRequested
          when pr.changesRequestedReviewers.isNotEmpty =>
        '🔴 Changes Requested (@${pr.changesRequestedReviewers.join(', @')})',
      ReviewDecision.changesRequested => '🔴 Changes Requested',
      ReviewDecision.reviewRequired when pr.needsReviewReRequest =>
        '🟠 Re-request Review (@${pr.unrequestedActiveReviewers.join(', @')})',
      ReviewDecision.reviewRequired when pr.targetReviewers.isNotEmpty =>
        '🟡 Review Required (@${pr.targetReviewers.join(', @')})',
      ReviewDecision.reviewRequired => '🟡 Review Required',
      _ => '⚪ None',
    };

String _formatCiBadgeMarkdown(CiStatus ciStatus) => switch (ciStatus) {
  CiStatus.success => '🟢 Passing',
  CiStatus.treeBroken => '🟠 Tree Broken (PR Clean)',
  CiStatus.actionRequired => '🟠 Action Required',
  CiStatus.failure => '🔴 Failing',
  CiStatus.pending => '⏳ Pending',
  _ => '⚪ None',
};

String _formatMergeableBadgeMarkdown(GhPr pr) {
  if (pr.isBlockedMergeState) {
    return '🧱 Blocked';
  }

  final label = switch (pr.mergeable) {
    MergeableState.mergeable => '✅ Yes',
    MergeableState.conflicting => '⚠️ Conflicting',
    _ => pr.isInMergeQueue ? '✅ Yes' : '⚪ Unknown',
  };
  return pr.isInMergeQueue ? '$label (🔀 Queue)' : label;
}

String _formatLocalMappingMarkdown(LocalBranchStatus? loc) {
  if (loc == null) return 'Local: ⚪ Not checked out';
  final dirName = p.basename(loc.repoPath);
  return 'Local: ${loc.displayStatus} ([$dirName](file://${loc.repoPath}))';
}

/// Renders human-readable colorized terminal output.
String renderTerminalReport(List<GhPr> prs, {DateTime? currentTime}) {
  final now = currentTime ?? DateTime.now();
  final categorized = categorizePullRequests(prs);

  final buffer = StringBuffer()
    ..writeln('''
======================================================================
${styleBold.wrap('🐙 GITHUB PULL REQUEST OVERVIEW')}
======================================================================''');

  if (prs.isEmpty) {
    buffer.writeln('\nNo open pull requests found. 🎉\n');
    return buffer.toString();
  }

  _writeTerminalSection(
    buffer,
    title: green.wrap(styleBold.wrap('🚀 READY TO MERGE')!)!,
    subtitle: 'Approved by reviewers and all CI checks passing:',
    prs: categorized.readyToMerge,
    now: now,
  );

  _writeTerminalSection(
    buffer,
    title: red.wrap(
      styleBold.wrap('⚠️  ACTION NEEDED (Blocked / Failing / Conflicts)')!,
    )!,
    subtitle: 'Requires code fixes, rebase, or review feedback resolution:',
    prs: categorized.actionNeeded,
    now: now,
  );

  _writeTerminalSection(
    buffer,
    title: yellow.wrap(styleBold.wrap('🟡 IN REVIEW QUEUE')!)!,
    subtitle: 'Active PRs awaiting reviewer feedback:',
    prs: categorized.inReview,
    now: now,
  );

  _writeTerminalSection(
    buffer,
    title: styleDim.wrap(styleBold.wrap('⚪ DRAFTS & WORK IN PROGRESS')!)!,
    subtitle: 'Work-in-progress draft pull requests:',
    prs: categorized.drafts,
    now: now,
  );

  _writeTerminalSection(
    buffer,
    title: styleDim.wrap(
      styleBold.wrap('📦 ARCHIVED REPOSITORIES (Read-Only)')!,
    )!,
    subtitle: 'Repositories are archived; pull requests cannot be modified:',
    prs: categorized.archived,
    now: now,
  );

  final summary =
      'Total Open: ${prs.length} | '
      '🚀 Ready: ${categorized.readyToMerge.length} | '
      '⚠️ Action: ${categorized.actionNeeded.length} | '
      '🟡 Review: ${categorized.inReview.length} | '
      '⚪ Drafts: ${categorized.drafts.length} | '
      '📦 Archived: ${categorized.archived.length}';

  buffer.writeln('''

----------------------------------------------------------------------
${styleBold.wrap('Summary:')} $summary
----------------------------------------------------------------------''');

  return buffer.toString();
}

void _writeTerminalSection(
  StringBuffer buffer, {
  required String title,
  required String subtitle,
  required List<GhPr> prs,
  required DateTime now,
}) {
  if (prs.isEmpty) return;
  buffer
    ..writeln('\n$title')
    ..writeln(styleDim.wrap('   $subtitle')!);
  for (final pr in prs) {
    _writePrItem(buffer, pr, now);
  }
}

void _writePrItem(StringBuffer buffer, GhPr pr, DateTime now) {
  final prTag =
      styleBold.wrap('${pr.repository}#${pr.number}') ??
      '${pr.repository}#${pr.number}';
  final touched = formatTouchedTerminal(pr.updatedAt, currentTime: now);

  final statusBadges = <String>[];
  if (pr.isRepoArchived) {
    statusBadges.add(styleDim.wrap('[Archived Repo]') ?? '[Archived Repo]');
  }
  if (pr.isDraft) {
    statusBadges.add(styleDim.wrap('[Draft]') ?? '[Draft]');
  }

  statusBadges
    ..add(_formatReviewBadgeTerminal(pr))
    ..add(_formatCiBadgeTerminal(pr));
  if (pr.isInMergeQueue) {
    statusBadges.add(cyan.wrap('🔀 In Merge Queue') ?? '🔀 In Merge Queue');
  }
  if (pr.isBlockedMergeState) {
    statusBadges.add(red.wrap('🧱 Blocked') ?? '🧱 Blocked');
  }
  if (pr.mergeable == MergeableState.conflicting) {
    statusBadges.add(red.wrap('⚠️ Conflicting') ?? '⚠️ Conflicting');
  }

  buffer
    ..writeln('\n  • $prTag: ${pr.title}')
    ..writeln('    URL:     ${pr.url}')
    ..writeln('    Status:  ${statusBadges.join(' | ')}')
    ..writeln('    Branch:  ${pr.headRefName} ➔ ${pr.baseRefName}')
    ..writeln('    Touched: $touched');

  if (pr.mergeable == MergeableState.conflicting) {
    final conflictLine =
        red.wrap(
          '⚠️ Blocked by merge conflicts with origin/${pr.baseRefName} '
          '(run: git fetch origin ${pr.baseRefName} && git merge origin/${pr.baseRefName})',
        ) ??
        '⚠️ Blocked by merge conflicts with origin/${pr.baseRefName} '
            '(run: git fetch origin ${pr.baseRefName} && git merge origin/${pr.baseRefName})';
    buffer.writeln('    Merge:   $conflictLine');
  }

  if (pr.ciDetail != null && pr.ciDetail!.trim().isNotEmpty) {
    buffer.writeln('    Checks:  ${pr.ciDetail!.trim()}');
  }

  if (pr.context != null && pr.context!.trim().isNotEmpty) {
    buffer.writeln('    Context: ${pr.context!.trim()}');
  }

  if (pr.localStatus != null) {
    final loc = pr.localStatus!;
    final locDesc = p.basename(loc.repoPath);
    final wtTag = loc.isWorktree ? ' (worktree)' : '';
    buffer.writeln(
      '    Local:   ${loc.displayStatus} [$locDesc$wtTag at ${loc.repoPath}]',
    );
  }
}

String _formatReviewBadgeTerminal(GhPr pr) {
  String formatRequested(String label, [List<String>? list]) {
    final targets = list ?? pr.targetReviewers;
    final text = targets.isNotEmpty
        ? '$label (@${targets.join(', @')})'
        : label;
    return yellow.wrap(text) ?? text;
  }

  return switch (pr.reviewDecision) {
    ReviewDecision.approved when pr.mergeable == MergeableState.conflicting =>
      green.wrap('Approved (Conflicting)') ?? 'Approved (Conflicting)',
    ReviewDecision.approved => green.wrap('Approved') ?? 'Approved',
    ReviewDecision.changesRequested when pr.needsReviewReRequest =>
      formatRequested(
        'Changes Requested · Re-request',
        pr.unrequestedActiveReviewers,
      ),
    ReviewDecision.changesRequested
        when pr.requestedReviewers.isNotEmpty &&
            pr.unrequestedActiveReviewers.isEmpty =>
      formatRequested('Re-review Requested'),
    ReviewDecision.changesRequested
        when pr.totalReviewThreads > 0 &&
            pr.unresolvedReviewThreads == 0 &&
            pr.hasAuthorRespondedSinceLastReview =>
      yellow.wrap('Changes Requested (Resolved: Re-review Needed)') ??
          'Changes Requested (Resolved: Re-review Needed)',
    ReviewDecision.changesRequested
        when pr.changesRequestedReviewers.isNotEmpty =>
      red.wrap(
            'Changes Requested (@${pr.changesRequestedReviewers.join(', @')})',
          ) ??
          'Changes Requested (@${pr.changesRequestedReviewers.join(', @')})',
    ReviewDecision.changesRequested =>
      red.wrap('Changes Requested') ?? 'Changes Requested',
    ReviewDecision.reviewRequired when pr.needsReviewReRequest =>
      formatRequested('Re-request Review', pr.unrequestedActiveReviewers),
    ReviewDecision.reviewRequired => formatRequested('Review Required'),
    _ => 'No Reviewers',
  };
}

String _formatCiBadgeTerminal(GhPr pr) => switch (pr.ciStatus) {
  CiStatus.success => green.wrap('CI: Passing') ?? 'CI: Passing',
  CiStatus.treeBroken =>
    yellow.wrap('CI: Tree Broken (PR Clean)') ?? 'CI: Tree Broken (PR Clean)',
  CiStatus.actionRequired =>
    yellow.wrap('CI: Action Required') ?? 'CI: Action Required',
  CiStatus.failure => red.wrap('CI: Failing') ?? 'CI: Failing',
  CiStatus.pending => yellow.wrap('CI: Pending') ?? 'CI: Pending',
  _ => styleDim.wrap('CI: None') ?? 'CI: None',
};

/// Renders machine-readable JSON output.
String renderJsonOutput(List<GhPr> prs, {DateTime? currentTime}) {
  final now = currentTime ?? DateTime.now();
  final categorized = categorizePullRequests(prs);

  Map<String, dynamic> prToJson(GhPr pr) => {
    'number': pr.number,
    'title': pr.title,
    'url': pr.url,
    'author': pr.author,
    'repository': pr.repository,
    'repoUrl': pr.repoUrl,
    'isRepoArchived': pr.isRepoArchived,
    'isDraft': pr.isDraft,
    'state': pr.state,
    'reviewDecision': pr.reviewDecision,
    'requestedReviewers': pr.requestedReviewers,
    'activeReviewers': pr.activeReviewers,
    'targetReviewers': pr.targetReviewers,
    'unrequestedActiveReviewers': pr.unrequestedActiveReviewers,
    'needsReviewReRequest': pr.needsReviewReRequest,
    'hasAuthorRespondedSinceLastReview': pr.hasAuthorRespondedSinceLastReview,
    'isAlreadyPinged': pr.isAlreadyPinged,
    'lastAuthorCommentAt': pr.lastAuthorCommentAt?.toIso8601String(),
    'lastCommitAt': pr.lastCommitAt?.toIso8601String(),
    'lastReviewerActivityAt': pr.lastReviewerActivityAt?.toIso8601String(),
    'totalReviewThreads': pr.totalReviewThreads,
    'unresolvedReviewThreads': pr.unresolvedReviewThreads,
    'areAllReviewThreadsResolved':
        pr.totalReviewThreads > 0 && pr.unresolvedReviewThreads == 0,
    'ciStatus': pr.ciStatus,
    'ciDetail': pr.ciDetail,
    'mergeable': pr.mergeable,
    'mergeStateStatus': pr.mergeStateStatus,
    'isInMergeQueue': pr.isInMergeQueue,
    'headRefName': pr.headRefName,
    'headRefOid': pr.headRefOid,
    'baseRefName': pr.baseRefName,
    'updatedAt': pr.updatedAt.toIso8601String(),
    'touched': formatTimeAgo(pr.updatedAt, currentTime: now),
    'context': pr.context,
    'local': pr.localStatus == null
        ? null
        : {
            'path': pr.localStatus!.repoPath,
            'branch': pr.localStatus!.branchName,
            'shortSha': pr.localStatus!.shortSha,
            'isDirty': pr.localStatus!.isDirty,
            'isHeadMatching': pr.localStatus!.isHeadMatching,
            'isWorktree': pr.localStatus!.isWorktree,
            'status': pr.localStatus!.displayStatus,
          },
  };

  final data = {
    'summary': {
      'total': prs.length,
      'readyToMerge': categorized.readyToMerge.length,
      'actionNeeded': categorized.actionNeeded.length,
      'inReview': categorized.inReview.length,
      'drafts': categorized.drafts.length,
      'archived': categorized.archived.length,
    },
    'readyToMerge': categorized.readyToMerge.map(prToJson).toList(),
    'actionNeeded': categorized.actionNeeded.map(prToJson).toList(),
    'inReview': categorized.inReview.map(prToJson).toList(),
    'drafts': categorized.drafts.map(prToJson).toList(),
    'archived': categorized.archived.map(prToJson).toList(),
  };

  return const JsonEncoder.withIndent('  ').convert(data);
}
